"""Config command — create/edit AnywhereInput configuration files."""

import argparse
import shutil
from pathlib import Path

try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    yaml = None


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
CONFIG_DIR = PROJECT_ROOT / "config"

SETTINGS_EXAMPLE = CONFIG_DIR / "settings.yaml.example"
RECOVERY_EXAMPLE = CONFIG_DIR / "recovery.yaml.example"

SETTINGS_YAML = CONFIG_DIR / "settings.yaml"
RECOVERY_YAML = CONFIG_DIR / "recovery.yaml"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _ensure_config_dir() -> Path:
    """Create config/ directory if it doesn't exist."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    return CONFIG_DIR


def _read_example(path: Path) -> str:
    """Read a .example file and strip its leading comment header."""
    text = path.read_text(encoding="utf-8")
    # Strip the "REFERENCE ONLY" block comment (everything up to first YAML key)
    lines = []
    in_header = True
    for line in text.splitlines():
        if in_header:
            if line.startswith("#") and not line.strip().startswith("##"):
                continue  # skip reference header comments
            else:
                in_header = False
        lines.append(line)
    return "\n".join(lines).strip()


def _write_file(path: Path, content: str) -> None:
    """Write content to file with backup of existing."""
    if path.exists():
        backup = path.with_suffix(".yaml.bak")
        shutil.copy2(str(path), str(backup))
        print(f"  📄 Backed up → {backup}")
    path.write_text(content, encoding="utf-8")
    print(f"  ✍️  Created → {path}")


def _parse_yaml_simple(text: str) -> dict:
    """Parse YAML if available; fall back to reading as plain text."""
    if yaml:
        return yaml.safe_load(text) or {}
    return {"_raw": True, "_text": text}


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_init(subparser):  # type: ignore[no-untyped-def]
    """Register sub-commands for the config command."""

    parser = subparser.add_parser(
        "init",
        help="Generate default config files from examples.",
    )
    parser.add_argument(
        "--settings",
        action="store_true",
        default=True,  # default behavior
        help="Create settings.yaml from example",
    )
    parser.add_argument(
        "--recovery",
        action="store_true",
        default=False,
        help="Also create recovery.yaml from example",
    )
    parser.set_defaults(func=_cmd_init_run)

    view_parser = subparser.add_parser(
        "view",
        help="Show the current config file contents (or examples).",
    )
    view_parser.add_argument(
        "--settings",
        action="store_true",
        default=False,
        help="Show settings.yaml content",
    )
    view_parser.add_argument(
        "--recovery",
        action="store_true",
        default=False,
        help="Show recovery.yaml content",
    )
    view_parser.set_defaults(func=_cmd_view_run)

    edit_parser = subparser.add_parser(
        "edit",
        help="Open a config file in your default editor.",
    )
    edit_parser.add_argument(
        "--settings",
        action="store_true",
        default=False,
        help="Edit settings.yaml",
    )
    edit_parser.add_argument(
        "--recovery",
        action="store_true",
        default=False,
        help="Edit recovery.yaml",
    )
    edit_parser.set_defaults(func=_cmd_edit_run)

    # List available config types
    list_parser = subparser.add_parser(
        "list",
        help="List available configuration files and their status.",
    )
    list_parser.set_defaults(func=_cmd_list_run)


def _cmd_init_run(args: argparse.Namespace):
    """Handle `anywhereinput config init`."""
    _ensure_config_dir()

    # Always show which examples exist
    print("📋 Available configuration templates:")
    for ex in CONFIG_DIR.glob("*.example"):
        status = "✓ exists" if ex.exists() else "✗ missing"
        print(f"  {ex.name:30s}  {status}")

    # Create settings.yaml from example
    if args.settings and SETTINGS_EXAMPLE.exists():
        content = _read_example(SETTINGS_EXAMPLE)
        if not content.startswith("#"):
            # Add a user-facing header
            content = (
                "# AnywhereInput — Server Configuration\n"
                "# Generated by `anywhereinput config init` on {}\n"
                "#\n"
                "# This file IS loaded at startup. Settings here become server defaults.\n"
                "# CLI flags (--fps, --quality, etc.) override these values.\n"
                "# For user-specific overrides, create config/local_settings.yaml (gitignored).\n\n"
            ).format(_now()) + content
        _write_file(SETTINGS_YAML, content)

    # Create recovery.yaml from example (opt-in via --recovery flag)
    if args.recovery or getattr(args, "all", False):
        if RECOVERY_EXAMPLE.exists():
            content = _read_example(RECOVERY_EXAMPLE)
            _write_file(RECOVERY_YAML, content)

    print("\n✅ Done! Config files created in config/")


def _cmd_view_run(args: argparse.Namespace):
    """Handle `anywhereinput config view`."""
    # Default to showing settings if neither flag is given
    if not args.settings and not args.recovery:
        args.settings = True

    if args.settings:
        path = SETTINGS_YAML if SETTINGS_YAML.exists() else SETTINGS_EXAMPLE
        if not path.exists():
            print("  No settings config found.")
            return
        print(f"\n# --- {path} ---")
        print(path.read_text())

    if args.recovery:
        path = RECOVERY_YAML if RECOVERY_YAML.exists() else RECOVERY_EXAMPLE
        if not path.exists():
            print("  No recovery config found.")
            return
        print(f"\n# --- {path} ---")
        print(path.read_text())


def _cmd_edit_run(args: argparse.Namespace):
    """Handle `anywhereinput config edit`."""
    import subprocess

    # Default to settings if neither flag is given
    if not args.settings and not args.recovery:
        args.settings = True

    if args.settings:
        target = SETTINGS_YAML
    else:
        target = RECOVERY_YAML

    if not target.exists():
        print(
            f"  No {target.name} to edit yet. Run `anywhereinput config init` first.\n"
        )
        return

    editor = _get_editor()
    try:
        subprocess.run([editor, str(target)])
        print(f"\n  ✍️  Saved changes to {target}")
    except (FileNotFoundError, OSError) as e:
        print(f"  ❌ Could not open editor '{editor}': {e}")
        print("     Set your EDITOR or VISUAL env variable, or edit manually:")
        print(f"       nano {target}")


def _cmd_list_run(args: argparse.Namespace):
    """Handle `anywhereinput config list`."""
    cfg_dir = _ensure_config_dir()

    print(f"\n📁 {cfg_dir}\n")
    for f in sorted(cfg_dir.iterdir()):
        size = f"{f.stat().st_size:>8}"
        if f.suffix == ".example":
            kind = "template"
        elif f.name.endswith(".bak"):
            kind = "backup"
        else:
            kind = "config"
        print(f"  {kind:10s}  {f.name:<30s}  {size}B")

    print("\n📖 Settings config — use as a reference for --fps, --quality, etc.")
    print("   or copy values to your launcher scripts.\n")
    print("🔧 Recovery config — tune capture engine health-check & backoff behavior.\n")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _get_editor() -> str:
    """Return the user's preferred text editor."""
    for var in ("EDITOR", "VISUAL"):
        val = __import__("os").environ.get(var)
        if val:
            return val.split()[0]
    # Platform defaults
    import platform

    if platform.system() == "Windows":
        return "notepad"
    return "nano"


def _now() -> str:
    from datetime import datetime

    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


# ---------------------------------------------------------------------------
# Main entry point (called by launcher.py when --config is used)
# ---------------------------------------------------------------------------


def register_config_parser(parser):
    """Add the config sub-parser to a parent parser."""

    subparsers = parser.add_subparsers(dest="command", help="Commands")
    config_parser = subparsers.add_parser(
        "config",
        help="Manage configuration files (init, view, edit, list).",
        description=(
            "Generate, view, or edit AnywhereInput configuration.\n\n"
            "Usage:\n"
            "  anywhereinput config init          Create default config files\n"
            "  anywhereinput config init --recovery   Also create recovery.yaml\n"
            "  anywhereinput config list           List available configs\n"
            "  anywhereinput config view           Show config contents\n"
            "  anywhereinput config edit           Open in $EDITOR\n"
        ),
    )

    config_subparsers = config_parser.add_subparsers(
        dest="config_command", help="Sub-command"
    )
    cmd_init(config_subparsers)
    config_parser.set_defaults(func=lambda args: _cmd_list_run(args))


def _run_config_command():
    """Run the config command standalone (for testing)."""
    parser = argparse.ArgumentParser(prog="anywhereinput-config")
    subparsers = parser.add_subparsers(dest="command", help="Command")
    cmd_init(subparsers)

    args = parser.parse_args()
    if hasattr(args, "func"):
        args.func(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    _run_config_command()
